pipeline{
    agent any
    tools{
        jdk 'jdk17'
        nodejs 'node14'
    }
    environment {
       // SCANNER_HOME=tool 'sonar-scanner'
        AWS_DEFAULT_REGION = 'us-west-2'
        ECR_REPOSITORY_URI = 'public.ecr.aws/i5k2v6g1/frontend'
    }
    stages {
        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/Vishvanath-Patil/Jenkins-EKS-ECR-Argocd-Monitoring-Three-Tier-Project.git'
            }
        }
        
    
     
        stage('Authenticate to ECR') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'aws-ecr-public', variable: 'AWS_CREDENTIALS')]) {
                        def loginCommand = "aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION}"
                        def dockerLoginCommand = "${loginCommand} | docker login --username AWS --password-stdin ${ECR_REPOSITORY_URI}"
                        sh dockerLoginCommand
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t frontend frontend'
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                script {
                    sh "docker tag frontend:latest ${ECR_REPOSITORY_URI}/frontend:latest"
                }
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    sh "docker push ${ECR_REPOSITORY_URI}/frontend:latest"
                }
            }
        }
    }
}
      
